name: Format MicroPython Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff with MicroPython-friendly config
        uses: astral-sh/ruff-action@v3
        with:
          args: check --select ALL --ignore F821,F401,E402 --exit-zero

      - name: Format code using Ruff
        run: ruff format .

      - name: Commit and push formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply Ruff formatting (MicroPython-safe)"
